export const PRODUCT = {
  title: "AI⁴ Wallet Preview",
  subtitle: "Constrain authority before you sign.",
  custody: "You sign. AI⁴ cannot move funds.",
  verify: "Identity verification: Preview / Production verifier not active.",
  signingUnavailable: "Signing readiness: Unavailable. Phase 0 does not request signatures.",
  signingNotReady: "Signing readiness: Not ready. Phase 0 does not request signatures.",
  phase: "Phase 1 DevNet preview. Local signature only. No broadcast.",
  postureDevnetOnly: "DEVNET ONLY",
  postureLocalSignatureOnly: "LOCAL SIGNATURE ONLY",
  postureNotBroadcast: "NOT BROADCAST",
  genesisNotChecked: "Genesis: not checked.",
  genesisChecking: "Genesis: checking.",
  genesisVerified: "Genesis verified.",
  genesisFailed: "Genesis check failed.",
  phase1Unavailable: "Signing status: Unavailable.",
  phase1Preparing: "Signing status: Preparing.",
  phase1Ready: "Signing status: Ready.",
  phase1Signing: "Signing status: Signing.",
  phase1Signed: "Signing status: Signed locally. Not broadcast.",
  phase1Failed: "Signing status: Failed.",
  prepareButton: "Prepare DevNet transfer",
  signButton: "Sign transaction",
  notBroadcast: "Not broadcast.",
  auditNote: "Approved binding SHA-256 is an audit digest. It does not authorize this signature.",
} as const;
